<Project Sdk="Microsoft.NET.Sdk">
  <!-- Datenzugriffsschicht: EF Core + SQLite -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(IdentityVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EfCoreVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BE\BE.csproj" />
  </ItemGroup>
</Project>
